### Get Projects
GET http://localhost:8080/api/meta/projects
Authorization: Basic user password
Accept: application/json

### Create Project
POST http://localhost:8080/api/meta/projects
Authorization: Basic user password
Content-Type: application/json
Accept: application/json

{
  "name": "My first test project",
  "description": "This is my first test project",
  "startsAt": "2023-05-12T12:34:56Z",
  "endsAt": "2023-05-13T10:30:00Z"
}

### Get Project by ID
GET http://localhost:8080/api/meta/projects/
Authorization: Basic user password
Accept: application/json


### Delete Project
DELETE http://localhost:8080/api/meta/projects/